#!/usr/bin/env python

""" User registers commands with CommandGroups """

import os
import sys
from collections import OrderedDict

from knack import CLI
from knack.commands import CLICommandsLoader, CommandSuperGroup

def a_test_command_handler():
    return [{'a': 1, 'b': 1234}, {'a': 3, 'b': 4}]


def hello_command_handler():
    return ['hello', 'world']


class MyCommandsLoader(CLICommandsLoader):

    def load_command_table(self, args):
        with CommandSuperGroup(__name__, self, '__main__#{}') as sg:
            with sg.group('hello') as g:
                g.command('world', 'hello_command_handler', confirmation=True)
            with sg.group('abc') as g:
                g.command('list', 'a_test_command_handler')
                g.command('show', 'a_test_command_handler')
        return OrderedDict(self.command_table)

mycli = CLI(cli_name='exapp2', config_dir=os.path.join('~', '.exapp2'), config_env_var_prefix='exapp2', commands_loader_cls=MyCommandsLoader)
exit_code = mycli.invoke(sys.argv[1:])
sys.exit(exit_code)
