#!/usr/bin/env python

""" User registers commands with CLICommand objects directly """

import os
import sys
from collections import OrderedDict

from knack import CLI
from knack.commands import CLICommandsLoader, CLICommand

def a_test_command_handler(h):
    return [{'a': 1, 'b': 1234}, {'a': 3, 'b': 4}]


class MyCommandsLoader(CLICommandsLoader):

    def load_command_table(self, args):
        self.command_table['abc xyz'] = CLICommand(self.cli_ctx, 'abc xyz', a_test_command_handler)
        self.command_table['abc list'] = CLICommand(self.cli_ctx, 'abc list', a_test_command_handler)
        return OrderedDict(self.command_table)

mycli = CLI(cli_name='exapp1', config_dir=os.path.join('~', '.exapp1'), commands_loader_cls=MyCommandsLoader)
exit_code = mycli.invoke(sys.argv[1:])
sys.exit(exit_code)
