#!/usr/bin/env python

""" User registers commands with cli_commands """

import os
import sys
from collections import OrderedDict

from knack import CLI
from knack.commands import CLICommandsLoader, CLICommand

def a_test_command_handler():
    return [{'a': 1, 'b': 1234}, {'a': 3, 'b': 4}]


def hello_command_handler():
    return ['hello', 'world']


class MyCommandsLoader(CLICommandsLoader):

    def load_command_table(self, args):
        self.cli_command(__name__, 'hello', '__main__#hello_command_handler', confirmation=True)
        self.cli_command(__name__, 'abc show', '__main__#a_test_command_handler')
        self.cli_command(__name__, 'abc list', '__main__#a_test_command_handler')
        return OrderedDict(self.command_table)

mycli = CLI(cli_name='exapp2', config_dir=os.path.join('~', '.exapp2'), config_env_var_prefix='exapp2', commands_loader_cls=MyCommandsLoader)
exit_code = mycli.invoke(sys.argv[1:])
sys.exit(exit_code)
